-- 08_purchase_requests.sql — the PR recap tabs, and which ledger row paid each line.
--
-- GENERATED by `08_pr_sheet.py` from the `2026 PURCHASE-PAYMENT TRACKER`
-- workbook. Edit the script or its template (`08_purchase_requests.head.sql`),
-- not this file.
--
-- ── What it reads ───────────────────────────────────────────────────────
--
-- Three tabs: `AUGUST PR RECAP`, `APROVE PR-27082026`, `SEPTEMBER PR RECAP`.
-- A line not paid in one recap was copied into the next, so the three tabs
-- are fewer lines than they are rows. The script folds the copies into one
-- line each and records every copy in `ops_core.legacy_map` as `superseded`,
-- pointing at the line it became — so *where did row 142 of AUGUST go* has an
-- answer.
--
-- ── What it writes ──────────────────────────────────────────────────────
--
--   ops_procure.pr_documents     one per LINE ID prefix the sheet carries, and
--                                one per request date for lines that had none
--   ops_procure.pr_lines         the request as the latest tab states it
--   ops_procure.pr_approvals     the GOODS tick, on the day it was given
--   ops_acct.payment_allocations the ledger transaction that paid the line
--
-- The allocation is the cross-reference both ways: a transaction's allocations
-- name the lines it paid (`pr_line_no`), and a line's coverage is the sum of
-- allocations naming it.
--
-- ── The owner's rule: paid on the day it was approved ───────────────────
--
-- Where the sheet dates the approval (AUGUST's metadata, APROVE 27-08's release
-- columns) the ledger was searched from that day. Where it does not, the
-- approval is dated by the transaction that paid it. See the script's header
-- for the search itself, and the twenty rows read by hand.
--
-- ── What it does not do ─────────────────────────────────────────────────
--
-- **It creates no ledger transaction.** A line the sheet calls paid and the
-- ledger has no row for gets no allocation and a note in the map saying so.
-- Every balance here is the sum of the ledger and agrees with the bank to the
-- rupiah; a transaction invented to satisfy a spreadsheet would break that on
-- a screen that looks identical to one that is right.
--
-- **It never invents a reference.** A vendor, project, unit or category that
-- does not resolve lands null, with the sheet's text kept in the map note.
--
-- **It changes no transaction.** Where the sheet and the ledger disagree on an
-- amount, the allocation carries the sheet's figure capped at what the
-- transaction holds, and both numbers stay as they were written.
--
-- Idempotent through `ops_core.legacy_map` (`source_table = 'sheet.pr_recap'`):
-- a second run stages nothing.

\set ON_ERROR_STOP on

begin;

create temp table _run on commit drop as select gen_random_uuid() as run_id;

create temp table _sheet (
  ref          text primary key,   -- the copy that wins, e.g. `APR7`
  refs         text not null,      -- every copy, oldest tab first
  doc_no       text not null,
  line_no      int  not null,
  req_date     date not null,
  requester    text,
  project      text,
  description  text not null,
  qty          numeric,
  uom          text,
  unit_raw     text,
  unit_price   numeric,
  item_total   numeric not null,
  vendor_raw   text,
  category     ops_procure.pr_category_t,
  category_raw text,
  purpose      text,
  approved     boolean not null,
  approved_at  timestamp,          -- WIB, as the sheet writes it
  approved_how text,
  approved_by  text,
  paid         numeric,
  cancelled_at timestamp,
  cancelled_by text,
  note         text
) on commit drop;

insert into _sheet values
/*@LINES@*/;

create temp table _alloc (ref text, trx_no text, amount numeric, how text) on commit drop;
insert into _alloc values
/*@ALLOCS@*/;

create temp table _carried (ref text, into_ref text) on commit drop;
insert into _carried values
/*@CARRIED@*/;

-- ── staging: only what the map has not seen ─────────────────────────────
create temp table _staged on commit drop as
select s.*,
       s.doc_no || '-L' || lpad(s.line_no::text, 2, '0') as line_no_full,
       coalesce(ru.id, sh.id)                          as requested_by,
       p.id                                            as project_id,
       coalesce(
         (select v.id from ops_procure.vendors v
           where v.merged_into is null
             and (upper(btrim(v.name)) = upper(btrim(s.vendor_raw))
                  or upper(btrim(s.vendor_raw)) = any (select upper(btrim(a)) from unnest(v.aka) a))
           order by v.code limit 1),
         -- canonical form, and only when exactly one vendor has it (as 07)
         (select min(v.id::text)::uuid from ops_procure.vendors v
           where v.merged_into is null
             and regexp_replace(upper(v.name), '[^A-Z0-9]', '', 'g')
               = regexp_replace(upper(s.vendor_raw), '[^A-Z0-9]', '', 'g')
          having count(*) = 1)
       )                                               as vendor_id
  from _sheet s
  left join ops_core.users ru on ru.email = s.requester
  join ops_core.users sh on sh.email = 'shared@talaliving.com'
  left join ops_procure.projects p on upper(p.name) = s.project
 where not exists (select 1 from ops_core.legacy_map m
                    where m.source_table = 'sheet.pr_recap' and m.source_id = s.ref);

-- ── documents ───────────────────────────────────────────────────────────
insert into ops_procure.pr_documents
  (doc_no, doc_type, status, requested_by, project_id, created_at, submitted_at)
select d.doc_no, 'PR', 'SUBMITTED',
       (array_agg(d.requested_by order by d.line_no))[1],
       -- a document names a project only when every line on it agrees
       case when count(distinct d.project_id) = 1 and count(*) = count(d.project_id)
            then min(d.project_id::text)::uuid end,
       (min(d.req_date) + time '09:00') at time zone 'Asia/Jakarta',
       (min(d.req_date) + time '09:00') at time zone 'Asia/Jakarta'
  from _staged d
 group by d.doc_no
on conflict (doc_no) do nothing;

-- The number counter learns every day this import used, so the next PR minted
-- on 23 Sep is `_02` rather than a unique violation.
insert into ops_core.doc_numbers (prefix, day, seq)
select 'pr', to_date(substr(doc_no, 4, 8), 'YY-MM-DD'), max(split_part(doc_no, '_', 2)::int)
  from _staged group by 2
on conflict (prefix, day) do update
  set seq = greatest(ops_core.doc_numbers.seq, excluded.seq);

-- ── lines ───────────────────────────────────────────────────────────────
insert into ops_procure.pr_lines
  (doc_id, doc_no, line_no, description, qty, uom, unit_price, item_total,
   vendor_id, category, purpose, created_at, removed_at, removed_by)
select d.id, s.doc_no, s.line_no, s.description, s.qty, s.uom, s.unit_price, s.item_total,
       s.vendor_id, s.category, s.purpose,
       (s.req_date + time '09:00') at time zone 'Asia/Jakarta',
       s.cancelled_at at time zone 'Asia/Jakarta',
       case when s.cancelled_at is not null
            then coalesce((select id from ops_core.users where email = s.cancelled_by),
                          (select id from ops_core.users where email = 'shared@talaliving.com')) end
  from _staged s
  join ops_procure.pr_documents d on d.doc_no = s.doc_no
on conflict (line_no_full) do nothing;

-- ── approvals: GOODS, by EJO, on the day the sheet says ─────────────────
insert into ops_procure.pr_approvals
  (line_id, step, approved, approved_qty, approved_amount,
   recorded_by, recorded_by_email, recorded_at, channel)
select l.id, 'GOODS', true, s.qty, s.item_total,
       u.id, s.approved_by, s.approved_at at time zone 'Asia/Jakarta', 'sheet'
  from _staged s
  join ops_procure.pr_lines l on l.line_no_full = s.line_no_full
  left join ops_core.users u on u.email = s.approved_by
 where s.approved
   and not exists (select 1 from ops_procure.pr_approvals a where a.line_id = l.id);

-- ── payments: the cross-reference ───────────────────────────────────────
create temp table _alloc_new on commit drop as
select a.ref, a.trx_no, a.amount, a.how, t.id as trx_id, s.line_no_full,
       case when ac.code = 'PETTY CASH' then 'cash' else 'transfer' end::ops_acct.alloc_method_t as method
  from _alloc a
  join _staged s on s.ref = a.ref
  left join ops_acct.transactions t on t.trx_no = a.trx_no and t.status <> 'VOID'
  left join ops_acct.accounts ac on ac.id = t.account_id;

do $$
begin
  if exists (select 1 from _alloc_new where trx_id is null) then
    raise exception 'allocation names a transaction that is not in the ledger: %',
      (select string_agg(trx_no, ', ') from _alloc_new where trx_id is null);
  end if;
end $$;

with ins as (
  insert into ops_acct.payment_allocations (trx_id, pr_line_no, amount, method, allocated_by)
  select n.trx_id, n.line_no_full, n.amount, n.method,
         (select id from ops_core.users where email = 'it@talaliving.com')
    from _alloc_new n
  returning id, trx_id, pr_line_no
)
insert into ops_core.legacy_map (source_table, source_id, target_table, target_id, outcome, note, run_id)
select 'sheet.pr_recap.payment', n.ref || ' → ' || n.trx_no, 'ops_acct.payment_allocations', i.id,
       'imported', n.how, (select run_id from _run)
  from ins i
  join _alloc_new n on n.trx_id = i.trx_id and n.line_no_full = i.pr_line_no
on conflict (source_table, source_id) do nothing;

-- ── the map: every sheet row, and what it became ────────────────────────
insert into ops_core.legacy_map (source_table, source_id, target_table, target_id, outcome, note, run_id)
select 'sheet.pr_recap', s.ref, 'ops_procure.pr_lines', l.id, 'imported',
       nullif(concat_ws('; ',
         'approved ' || to_char(s.approved_at, 'DD Mon YYYY') || ' from ' || s.approved_how,
         case when s.vendor_raw is not null and s.vendor_id is null
              then 'vendor ' || quote_literal(s.vendor_raw) || ' resolves to nothing' end,
         case when s.project is not null and s.project_id is null
              then 'project ' || quote_literal(s.project) || ' is not a project here' end,
         case when s.cancelled_at is not null then 'CANCEL on the sheet — removed' end,
         s.note), ''),
       (select run_id from _run)
  from _staged s
  join ops_procure.pr_lines l on l.line_no_full = s.line_no_full
on conflict (source_table, source_id) do nothing;

insert into ops_core.legacy_map (source_table, source_id, target_table, target_id, outcome, note, run_id)
select 'sheet.pr_recap', c.ref, 'ops_procure.pr_lines', l.id, 'superseded',
       'earlier copy of ' || c.into_ref || ', carried forward to a later recap tab',
       (select run_id from _run)
  from _carried c
  join _sheet s on s.ref = c.into_ref
  join ops_procure.pr_lines l on l.line_no_full = s.doc_no || '-L' || lpad(s.line_no::text, 2, '0')
on conflict (source_table, source_id) do nothing;

-- ── what came across ────────────────────────────────────────────────────
\echo ''
\echo '── imported ────────────────────────────────────────────────────────'
select (select count(*) from ops_procure.pr_documents)                     as documents,
       (select count(*) from ops_procure.pr_lines)                         as lines,
       (select count(*) from ops_procure.pr_approvals)                     as approvals,
       (select count(*) from ops_acct.payment_allocations
         where superseded_by is null)                                      as allocations,
       (select count(distinct pr_line_no) from ops_acct.payment_allocations
         where superseded_by is null)                                      as lines_paid;

\echo ''
\echo '── the sheet against the ledger ────────────────────────────────────'
select round(sum(s.paid))                                                  as sheet_paid,
       round((select sum(a.amount) from ops_acct.payment_allocations a
               where a.superseded_by is null
                 and a.pr_line_no in (select doc_no || '-L' || lpad(line_no::text, 2, '0') from _sheet)))
                                                                           as allocated,
       count(*) filter (where s.paid > 0 and not exists (
         select 1 from _alloc a where a.ref = s.ref))                      as paid_no_ledger_row
  from _sheet s;

\echo ''
\echo '── no transaction may be allocated beyond its amount ───────────────'
select t.trx_no, t.amount_idr, sum(a.amount) as allocated
  from ops_acct.payment_allocations a
  join ops_acct.transactions t on t.id = a.trx_id
 where a.superseded_by is null
 group by t.trx_no, t.amount_idr
having sum(a.amount) > t.amount_idr;

commit;
