-- 0105_prod_bom_labour_kind.sql — labour becomes a line on the bill of material.
--
-- The owner's shape for costing (2026-09-23): a BOM line is *anything that
-- costs money to make one unit* — timber at 0,1 m³, coating at 1 litre, and
-- **tenaga kerja** at 1,5 hari × a day rate. So labour stops being one typed
-- figure on the product (`products.labour_cost`, D239) and becomes lines, each
-- with its own quantity and rate, summed like every other line.
--
-- Its own file because `alter type … add value` cannot be used in the same
-- transaction that adds it, and the hosted project applies each migration as
-- one transaction. `0106` is where the new value is used.
alter type ops_prod.bom_ref_t add value if not exists 'labour';
